### ISSUE TITLE
dev: make coinbase storage var a constructor argument rather than a hardcoded value

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1011]
make coinbase storage var a constructor argument rather than a hardcoded value

note:
- coinbase is an EVM address, more precisely an EOA of which the deployer owns the key (or they know that the coinbase owns the keys to this EOA)

**Comment by AryanGodara** [comment]
@enitrat Can you please assign this issue to me :)

**Comment by enitrat** [comment]
Hi @AryanGodara I'm clearing your assignement for this one, let me know if that's a problem

**Comment by prof-farworse** [comment]
Hi everyone, maybe I can give it a try?

**Comment by enitrat** [comment]
@prof-farworse Go ahead!

**Comment by prof-farworse** [comment]
@enitrat Thanks! ;-)

**Comment by enitrat** [comment]
Currently Coinbase is a hardcoded value defined here
https://github.com/kkrt-labs/kakarot/blob/da76e0e5e26f7242c35331473a02945773265195/src/kakarot/library.cairo#L52

We should make it a constructor argument so that it depends on the deployment variables and not a hardcoded value https://github.com/kkrt-labs/kakarot/blob/da76e0e5e26f7242c35331473a02945773265195/src/kakarot/library.cairo#L39-L46

This will require adapting the deployment scripts 
https://github.com/kkrt-labs/kakarot/blob/da76e0e5e26f7242c35331473a02945773265195/kakarot_scripts/deploy_kakarot.py#L55-L63

with a COINBASE value that can be a constant in the tests.

 The fixture file will need to be updated as well 
 https://github.com/kkrt-labs/kakarot/blob/da76e0e5e26f7242c35331473a02945773265195/tests/fixtures/EVM.cairo#L33-L39
 
 To clean the code, all direct usages of the coinbase in tests constant must be moved to a const variable.

**Comment by prof-farworse** [comment]
I posted a pull request for this issue. See my explanation there (and comment about the 2 failed checks).
