### ISSUE TITLE
dev: compute some statistics about validation and execute steps per transactions

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1195]
context: Ilia from Starkware is pushing to change core constants in the next Starknet mainnet version, 0.13.2. The update is scheduled for July and the decision will take place mid June. We want this update to allow Kakarot to be deployed and operate well on Starknet mainnet and testnet.

such constants are: step limit per transaction, divided between validate and execute steps; block size, block lifespan, and calldata limit per transaction.

### goal

- compute max steps in edge cases validate scenarios (biggest calldata in an L1 transaction, big contract deployment, etc)

- compute max steps in edge cases scenarios for execute step

bonus: compute median steps, mean steps

### results:

ability to give with good confidence the constants that will be unchangeable for the entirety of 0.13.2 and ability for Kakarot to operate on Starknet mainnet 

we want to avoid cases where Kakarot is deployed on Starknet mainnet but unpredictable certain operations are impossible (same example as when we discovered addLiquidity of Uniswap was 7m steps > 4m steps current per tx limit)

note: need scoping cc @ClementWalter

**Comment by enitrat** [comment]
### Validate

Validation is bounded by the amount of calldata sent with the transaction. When running validation, we need to 
1. Unpack the 31-bytes packed calldata into individual bytes
2. RLP-decode the transaction
3. Keccak-hash the tx to re-compute the message hash
4. verify the signature of the message hash

Steps 1,2,3 are dependant on the amount of data sent with the transaction. Considering that a contract has a 24kB size limit, and that deploying a UniswapV2Router contract of size 18kB takes 800k steps, we could extrapolate that in order to deploy the biggest contract possible we would ~1.1M steps would be enough for the validation step.

On the other hand, if we consider that the Ethereum block gas limit is 30M and that each non-zero byte of calldata consumes 16gas, one could send up to 1.8MB of calldata and the _theoritical_ requirement would be 75M steps for a transaction that big - but this is not a common use case that we aim to support.

**Comment by Eikix** [comment]
> ### Validate
> Validation is bounded by the amount of calldata sent with the transaction. When running validation, we need to
> 
> 1. Unpack the 31-bytes packed calldata into individual bytes
> 2. RLP-decode the transaction
> 3. Keccak-hash the tx to re-compute the message hash
> 4. verify the signature of the message hash
> 
> Steps 1,2,3 are dependant on the amount of data sent with the transaction. Considering that a contract has a 24kB size limit, and that deploying a UniswapV2Router contract of size 18kB takes 800k steps, we could extrapolate that in order to deploy the biggest contract possible we would ~1.1M steps would be enough for the validation step.
> 
> On the other hand, if we consider that the Ethereum [max calldata size](https://github.com/ethereum/go-ethereum/blob/2eb185c92b2655ceee91b730fc5904379fe0ff6f/core/txpool/blobpool/blobpool.go#L67) is 1MB, the _theoritical_ requirement would be ~50M steps for a transaction that big - but this is not a common use case that we aim to support.

Last step, as discussed, is to check the "sweet spot" for supported max KB in a single transaction. The tension is between DoS risk on the `__validate__` step on the Cairo side vs. widespread support for EVM transactions.
Can we check the median, or P99 (is that the correct word?) for L2 transactions?

**Comment by enitrat** [comment]
Analysis of ~1500 optimism transactions. 99.99% of have less than 50kb of calldata, which would pass validation of 2M. 

The most calldata-intensive seem to be related to [seaport](https://github.com/ProjectOpenSea/seaport)

![telegram-cloud-photo-size-4-5998950714505805715-y](https://github.com/kkrt-labs/kakarot/assets/60658558/41d58ce0-8f82-45e7-8a06-1e4420366ee3)

![telegram-cloud-photo-size-4-5998950714505805716-y](https://github.com/kkrt-labs/kakarot/assets/60658558/016e7fb7-2116-45b3-ab4a-55f8595c0460)

**Comment by ClementWalter** [comment]
Closing since becoming off topic with #1246
