### ISSUE TITLE
feat: use Argent multisig in the deploy script

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1411]
### Describe the Feature Request

We want to be able to use a multisig instead of the basic Argent account in the deployment script, for deploying Kakarot and other critical part of the stack.

### How

- [x] (if you don't have one) create an Argent mutlisg on sepolia
- [x] make a random tx while inspecting the network
- [x] retro engineer the call (should be clear, if not ask on Argent<>Kakarot tg group)
- [ ] update the `starknet.py` utils and `deploy_kakarot.py` script to use this multisig depending on the network

**Comment by eugypalu** [comment]
The sign functions used by the two libraries ([starknet.js](https://github.com/paulmillr/scure-starknet/blob/main/index.ts#L96) and [starknet_py](https://github.com/software-mansion-labs/crypto-cpp-py/blob/main/crypto_cpp_py/cpp_bindings.py#L135)) are different, and as a result, they produce different signatures for the same (`msg_hash`, `priv_key`), even though both signatures are valid within the context of their respective libraries.
I have ruled out other possible causes through testing with both libraries. At the signing step, the same hash is produced and the same key is used, so the steps leading up to the signature are correct, and the issue lies in the signature calculation.
However, this difference creates a compatibility problem with Argent’s API, which uses `starknet.js` to calculate transaction signatures. When a transaction is signed using `starknet_py`, the resulting signature is rejected by Argent’s API as `invalidSignature`
