### ISSUE TITLE
feat: Add Rust opcodes test against Madara/Katana

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot#619]
# Feature Request

Currently have implemented running rust tests against the Kakarot contract deployed on Madara.

Steps to run the tests from the branch:

- fork: https://github.com/danilowhk/kakarot-opcode-test
- add "@view execute" function on Kakarot
- adapt: .env (kakarot contract and class_hash)

View function code:

@view
func execute{
    syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr, bitwise_ptr: BitwiseBuiltin*
}(
    starknet_contract_address: felt,
    evm_contract_address: felt,
    bytecode_len: felt,
    bytecode: felt*,
    calldata_len: felt,
    calldata: felt*,
    value: felt,
    gas_limit: felt,
    gas_price: felt,
) -> (
    stack_accesses_len: felt,
    stack_accesses: felt*,
    stack_len: felt,
    memory_accesses_len: felt,
    memory_accesses: felt*,
    memory_bytes_len: felt,
    starknet_contract_address: felt,
    evm_contract_address: felt,
    return_data_len: felt,
    return_data: felt*,
    gas_used: felt,
) {
    return Kakarot.execute(
        starknet_contract_address,
        evm_contract_address,
        bytecode_len,
        bytecode,
        calldata_len,
        calldata,
        value,
        gas_limit,
        gas_price,
    );
}

Current observations:

- Results are not decoded and compared to expected results
- Currently, we are only calling the @view function, might be worth testing calling a @external function with internal variables change.

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by bajpai244** [comment]
Hello @danilowhk , I can work on this!

**Comment by jobez** [comment]
I just want to make the point that we should not replace our python tests with the rust-vm. If anything we should be comparing results between the two vms first. 

you also dont necessarily need to add any function, just compile this EVM fixture we have and have it deployed: https://github.com/kkrt-labs/kakarot/blob/main/tests/fixtures/EVM.cairo

**Comment by bajpai244** [comment]
So, adding a scope of work here to make this task more specific.

- Write a rust implementation using starkness-rs, which integrates the bytecode testing @danilowhk has done into our Kakarot main repo. This means running the tests defined in [this](https://github.com/danilowhk/kakarot-opcode-test/blob/main/test_cases.json) JSON file and testing we are getting the desired output.
- We can deploy the [following ](https://github.com/kkrt-labs/kakarot/blob/main/tests/fixtures/EVM.cairo) contract to the RPC to use the [execute](https://github.com/kkrt-labs/kakarot/blob/baa08057bf24c533748883fe2551a148d6cfcba3/tests/fixtures/EVM.cairo#L40) function exposed by it.
- The choice of sequencer for this should be a real tenet of Starknet.

Questions I have:
- The reason why we started with Rust was to make easy to use test sequencer of Katana and make this test run faster, but, now it seems like we want to test this onto the real testnet, do we still need Rust in that case? because I think a scripting language seems to be better suited for this and might want to add this one more test in python as well.

CC:
@Eikix , @danilowhk

**Comment by Eikix** [comment]
I think it's because we trust `starknet-rs` more, and would like to not add too many languages in the repo (if we add TS, it now has lots of dependencies)
Happy to hear challenges

Ideally as well, your rust code would be used later when we refactor python to rust

**Comment by Eikix** [comment]
That works for me btw!
@ClementWalter said we should deploy EVM.Cairo as part of our CI as well, I think it can be done now, as a first PR.

The issue would simply be -> add EVM.cairo in the deployments scripts

That way, we can retrieve the address of EVM.cairo from the deployments artifacts like we'll be doing for Kakarot main contracts.

**Comment by Eikix** [comment]
What is the status of this issue?
It appears it'll be done within ethereum/tests implementation?

afaiu we are deprioritizing this
