### ISSUE TITLE
dev: make EVM an implicit argument of EVM-modifying functions

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#885]
`func charge_gas{range_check_ptr}(self: model.EVM*, amount: felt) -> model.EVM* {`

takes the EVM as explicit parameters and returns a new instance. 
It could be refactored to

`func charge_gas{range_check_ptr, evm: model.EVM*}(amount: felt)  {`

**Comment by joseSalazar4** [comment]
Hey there! Could I take this one? I believe the idea is to modify the attributes of the EVM received so we don't create a new instance with almost all the parms being the same on the second instance creation, correct?

**Comment by enitrat** [comment]
@ClementWalter should we go forward with this?

**Comment by ClementWalter** [comment]
@joseSalazar4 it wouldn't save any steps actually, it's just to (possibly) increase readability. Tbh I'm not 100% sure that it'd be much better though, because the explicit `f(evm) -> evm` shows well that the `evm` is updated, as opposed to `f()`.

If you want to give it a try, please, but be aware of the fact that upon PR, when actually seing it, we may decide to close instead of merge

**Comment by ClementWalter** [comment]
(to be more precise, in Cairo Zero, using an implicit arg is exactly the same as defining the same arg (same name and type) as input and output

**Comment by joseSalazar4** [comment]
Your comment makes a lot of sense, this is better being explicit, agreed.
